services:
  tvservicecrm.server:
    image: ${DOCKER_REGISTRY-}tvservicecrmserver
    build:
      context: .
      dockerfile: TVServiceCRM.Server/Dockerfile
    ports:
      - 8080:8080
      - 8081:8081
    volumes:
      - test1:/app/VolumeDB

volumes:   # add this section
  test1: 
     external: true  