services:


  tvservicecrm.server:
    container_name: tvservicecrm.server
    image: alexpsychoson/tvservicecrmserver:latest
    build:
      context: .
      dockerfile: TVServiceCRM.Server/Dockerfile
    # ports:
    #   - 8080:8080
    #   - 8081:8081
    expose:
      - 8080
      - 8081

    volumes:
      - /mnt/tvsercivecrmvolume:/app/VolumeDB
      # - test1:/app/VolumeDB
      - ~/.aspnet/https:/https:ro

    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      # - ASPNETCORE_URLS=https://*:8081
      # - ASPNETCORE_HTTPS_PORT=8081
      - ASPNETCORE_Kestrel__Certificates__Default__Password=P@ssw0rd
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx


  nginx:
    container_name: nginx
    restart: unless-stopped
    image: nginx
    ports:
        - 80:80
        - 443:443
    volumes:
        - ./TVServiceCRM.Server/nginx.conf:/etc/nginx/nginx.conf
        - ./certbot/conf:/etc/letsencrypt
        - ./certbot/www:/var/www/certbot
  
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes: 
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email psychoson_alex3@hotmail.com -d www.alexps.gr -d 165.227.245.10 -d 164.92.183.31 --agree-tos



    

# volumes: 
#    test1: 
#      external: true  