services:


  tvservicecrm.server:
    container_name: tvservicecrm.server
    image: alexpsychoson/tvservicecrmserver:latest
    build:
      context: .
      dockerfile: TVServiceCRM.Server/Dockerfile
    ports:
      - 8080:8080
    expose:
      - 8080
    volumes:
      - /mnt/tvsercivecrmvolume:/app/VolumeDB
      # - test1:/app/VolumeDB
      # - ~/.aspnet/https:/https:ro
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://*:8080
      # - ASPNETCORE_HTTPS_PORT=8081
      # - ASPNETCORE_Kestrel__Certificates__Default__Password=P@ssw0rd
      # - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    networks:
      - nginx-network

  nginx:
    image: nginx:stable-alpine 
    restart: unless-stopped
    ports:
        - 80:80
        - 443:443
    volumes:
        - ./TVServiceCRM.Server/nginx:/etc/nginx/nginx
        - ./TVServiceCRM.Server/Certbot/config:/etc/letsencrypt
        - ./TVServiceCRM.Server/Certbot/www:/var/www/certbot
    environment:
        - NGINX_HOST=alexps.gr
    depends_on:
        - tvservicecrm.server
    networks:
      - nginx-network



  certbot:
    image: certbot/certbot
    volumes: 
      - ./TVServiceCRM.Server/Certbot/config:/etc/letsencrypt
      - ./TVServiceCRM.Server/Certbot/www:/var/www/certbot
    # command: certonly --webroot -w /var/www/certbot --force-renewal --email psychoson_alex3@hotmail.com -d www.alexps.gr -d alexps.gr --agree-tos
    restart: unless-stopped


networks:
  nginx-network:
      driver: bridge
    

volumes: 
   test1: 
     external: true  