services:


  tvservicecrm.server:
    container_name: tvservicecrm.server
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: TVServiceCRM.Server/Dockerfile
    ports:
      - 8080:8080
    expose:
      - 8080
    volumes:
      - /mnt/tvsercivecrmvolume:/app/VolumeDB
      # - test1:/app/VolumeDB
    restart: unless-stopped
    environment:
      - ASPNETCORE_URLS=http://*:8080
    networks:
      - nginx-network

  nginx:
    image: nginx:stable-alpine 
    restart: unless-stopped
    ports:
        - 80:80
        - 443:443
    volumes:
      - ./TVServiceCRM.Server/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./TVServiceCRM.Server/Certbot/config:/etc/letsencrypt:ro
      - ./TVServiceCRM.Server/Certbot/www:/usr/share/nginx/html/:ro
    environment:
        - NGINX_HOST=alexps.gr
    depends_on:
        - tvservicecrm.server
    links:
        - tvservicecrm.server
    networks:
      - nginx-network



  certbot:
    image: certbot/certbot
    volumes: 
      - ./TVServiceCRM.Server/Certbot/config:/etc/letsencrypt/:rw
      - ./TVServiceCRM.Server/Certbot/www:/usr/share/nginx/html/:rw
    # command: certonly --webroot -w /var/www/certbot --force-renewal --email psychoson_alex3@hotmail.com -d www.alexps.gr -d alexps.gr --agree-tos
    restart: unless-stopped


networks:
  nginx-network:
      driver: bridge
    

# volumes: 
#    test1: 
#      external: true  